language: python

python: 2.7

env:
    - TOXENV=check-manifest
    - TOXENV=cov-init
    - TOXENV=flake8
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy

install:
    - pip install tox

script:
    - tox

notifications:
  email: false
