language: python

python: 2.7

env:
  - TOXENV=check-manifest
  - TOXENV=cov-init
  - TOXENV=flake8
  - TOXENV=py27

install:
  - pip install tox

script:
  - tox -e $TOXENV

notifications:
  email: false
