---

sudo: false

language: python

matrix:
    include:
        - python: 2.7
          env: TOX_ENV=py27
        - python: 2.7
          env: TOX_ENV=lint
        - python: 2.7
          env: TOX_ENV=check-manifest
        - python: 2.7
          env: TOX_ENV=docs

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success:
  - coveralls

notifications:
  email: false
