language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "pypy"

env:
    - TOXENV=check-manifest
    - TOXENV=cov-init
    - TOXENV=flake8
    - TOXENV=py26
    - TOXENV=py27
    - TOXENV=py32
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35

install:
    - pip install tox

script:
    - tox

notifications:
  email: false
